### ISSUE TITLE
Multiprocessing of BIONIC evals

### ISSUE THREAD

**Issue by pravzK94** [duncster94/BIONIC-evals#5]
Hi,

I have run BIONIC for our mycobacterium-human network analysis in the month of march, 20222 and also would, like to implement the bionic evals for our work for more insightful outcomes.
Please, implement the multi-processing function for the same. 

Thanks in advance.
Regards
Praveena

**Comment by duncster94** [comment]
Thanks for opening an issue,

Currently there is a [pull request](https://github.com/duncster94/BIONIC-evals/pull/4) open which adds multi-processing functionality. I'll go through the PR and merge it in a day or so.

**Comment by pravzK94** [comment]
Thanks and I will be looking forward for the merge PR.

**Comment by duncster94** [comment]
Hi, [v0.2.0](https://github.com/duncster94/BIONIC-evals/releases/tag/v0.2.0) is now available. Both the gene function prediction and module detection evaluations now use multiprocessing.

Feel free to reopen the issue if you run into any problems!
