### ISSUE TITLE
can not install bioniceval

### ISSUE THREAD

**Issue by wenmm** [duncster94/BIONIC-evals#9]
Is there any other way to install bioniceval besides using poetry? I can't install it with poetry. this is the log file of poetry install. Bionic can be installed with pip, can bioniceval add pip as well? Thanks!
![image](https://github.com/duncster94/BIONIC-evals/assets/31941752/5e1b75f0-1e6b-4239-b0a8-41982850c28d)

**Comment by duncster94** [comment]
Hi, can you provide the full install log?

**Comment by wenmm** [comment]
Hi, this is the full log now, when I run poetry install for the first time, there's no responce, No matter how long it takes, I will be stuck here, so I ran it in the background several times. The picture above is all the results in the background.
![image](https://github.com/duncster94/BIONIC-evals/assets/31941752/dc862173-5816-416d-abf2-07c1568ed465)

**Comment by duncster94** [comment]
Hi, are you running on a cluster/machine without internet access? You might also want to check out [this](https://stackoverflow.com/questions/74960707/poetry-stuck-in-infinite-install-update).

If Poetry doesn't work then you can manually `pip install` the dependencies listed in the `pyproject.toml` file. You won't be able to use the `bioniceval` command but you should still be able to run it by calling `python main.py`.

**Comment by wenmm** [comment]
![image](https://github.com/duncster94/BIONIC-evals/assets/31941752/75949b4c-061e-4f21-a8b8-cd629bb3500e)
the internet is OK

**Comment by wenmm** [comment]
OK! thanks!

**Comment by wenmm** [comment]
I tried remove all the virtual environments, clear the cache, it did not work, still the same

**Comment by duncster94** [comment]
Hi, did you try manually installing the required packages via `pip`?

**Comment by wenmm** [comment]
I have solved this problem by only using modified  function_prediction.py, thank you for your responding, you are really nice!

**Comment by duncster94** [comment]
Glad it works! Thanks.
